name: 'Build and Test'
description: "Builds and tests a VIM project"
inputs:
  project_path:
    required: true
  package_name:
    required: true
  root_path:
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install additional tools
      run: sudo apt install nuget
      shell: bash
    - name: Check version
      run: ${{ inputs.root_path }}/scripts/check-nuget-version.sh ${{ inputs.project_path }} ${{ inputs.package_name }}
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build -c Release --no-restore
      shell: bash
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      shell: bash