name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout shared scripts
      uses: actions/checkout@v2
      with:
        repository: vimaec/ci-cd-scripts
        ref: refs/heads/main
        path: .github/
    - uses: ./.github/actions/publish-nuget
      with:
        project_path: << PROJECT_PATH >>
        package_name: << PACKAGE_NAME >>
        api_key: ${{secrets.NUGET_KEY}}
        root_path: ".github"
