name: 'Publish to NuGet'
description: 'Publishes a VIM project to NuGet.org'
inputs:
  project_path:
    description: 'The path to the .csproj file'
    required: true
  test_project_path:
    description: 'The path to the test .csproj file'
    required: false
    default: ''
  package_name:
    description: 'The project name used for publishing'
    required: true
  api_key:
    description: 'The API key for publishing to NuGet'
    required: true
  root_path:
    description: 'The root path where this repository is checked out'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Build and Test
      uses: ./actions/build-and-test
      with:
        project_path: ${{ inputs.project_path }}
        test_project_path: ${{ inputs.test_project_path }}
        package_name: ${{ inputs.package_name }}
        root_path: ${{ inputs.root_path }}

    - name: Pack NuGet package
      run: nuget pack ${{ inputs.project_path }} -Symbols -SymbolPackageFormat snupkg -OutputDirectory . -NonInteractive -Properties Configuration=Release -Exclude *.tt
      shell: bash
    - name: Push NuGet package
      run: nuget push ${{ inputs.package_name }}*.nupkg -ApiKey ${{ inputs.api_key }} -Source https://api.nuget.org/v3/index.json
      shell: bash
    - name: Push symbols
      run: nuget push ${{ inputs.package_name }}*.snupkg -ApiKey ${{ inputs.api_key }} -Source https://api.nuget.org/v3/index.json
      shell: bash
    - name: Tag commit
      run: ${{ inputs.root_path }}/scripts/tag-commit.sh ${{ inputs.project_path }}
      shell: bash