name: 'Publish to NuGet'
description: 'Publishes a VIM project to NuGet.org'
inputs:
  project_path:
    description: 'The path to the .csproj file'
    required: true
  test_project_path:
    description: 'The path to the test .csproj file'
    required: false
    default: ''
  package_name:
    description: 'The project name used for publishing'
    required: true
  api_key:
    description: 'The API key for publishing to NuGet'
    required: true
  root_path:
    description: 'The root path where this repository is checked out'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install additional tools
      run: sudo apt install nuget
      shell: bash
    - name: Check version
      # composite actions don't support if-statements yet
      run: |
        ! [[ "${{ inputs.package_name }}" == "" ]] && \
        ${{ inputs.root_path }}/scripts/check-nuget-version.sh ${{ inputs.project_path }} ${{ inputs.package_name }} \
        || true
      shell: bash

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }}
      shell: bash
    - name: Build
      run: dotnet build -c Release --no-restore ${{ inputs.project_path }}
      shell: bash
    - name: Test
      run: dotnet test -c Release ${{ inputs.test_project_path }}
      shell: bash

    - name: Pack NuGet package
      run: nuget pack ${{ inputs.project_path }} -Symbols -SymbolPackageFormat snupkg -OutputDirectory . -NonInteractive -Properties Configuration=Release -Exclude *.tt
      shell: bash
    - name: Push NuGet package
      run: nuget push ${{ inputs.package_name }}*.nupkg -ApiKey ${{ inputs.api_key }} -Source https://api.nuget.org/v3/index.json
      shell: bash

    - name: Tag commit
      run: ${{ inputs.root_path }}/scripts/tag-commit.sh ${{ inputs.project_path }}
      shell: bash